import { Category, SanitySlug } from './types'

export interface StaticCategory {
  id: string
  name: string
  slug: string
  description: string
  shortDesc: string
  image: string
  icon: string
  accentColor: string
}

export const CATEGORIES_DATA: StaticCategory[] = [
  {
    id: 'cat-1',
    name: 'Dung Môi Công Nghiệp',
    slug: 'dung-moi-cong-nghiep',
    description: 'Cung cấp cồn công nghiệp, Acetone, Toluen, Xylen, Butyl Acetate tiêu chuẩn cao cho các ngành sản xuất.',
    shortDesc: 'Acetone, Toluen, Xylen, Butyl...',
    image: '/images/categories/dung-moi-cong-nghiep.jpg',
    icon: '🧪',
    accentColor: 'from-blue-600 to-cyan-500',
  },
  {
    id: 'cat-2',
    name: 'Hóa Chất Công Nghiệp',
    slug: 'hoa-chat-cong-nghiep',
    description: 'Hóa chất cơ bản phục vụ toàn diện các nhà máy: Xút NaOH, Axit HCl, H2SO4, PAC, Javen, Clo.',
    shortDesc: 'Xút NaOH, Axit HCl, PAC, Clo...',
    image: '/images/categories/hoa-chat-cong-nghiep.jpg',
    icon: '⚙️',
    accentColor: 'from-slate-700 to-blue-600',
  },
  {
    id: 'cat-3',
    name: 'Hóa Chất Dệt Nhuộm',
    slug: 'hoa-chat-det-nhuom',
    description: 'Thuốc nhuộm hoạt tính, chất trợ nhuộm, chất cầm màu, chất tẩy trắng quang học chất lượng cao.',
    shortDesc: 'Thuốc nhuộm, trợ nhuộm, cầm màu...',
    image: '/images/categories/hoa-chat-det-nhuom.jpg',
    icon: '🎨',
    accentColor: 'from-purple-600 to-pink-500',
  },
  {
    id: 'cat-4',
    name: 'Hóa Chất In Ấn',
    slug: 'hoa-chat-in-an',
    description: 'Dung dịch pha mực in, nước rửa bản in, chất chống dính, dung môi bay hơi nhanh cho ngành in ấn bao bì.',
    shortDesc: 'Nước rửa bản, pha mực, dung môi...',
    image: '/images/categories/hoa-chat-in-an.jpg',
    icon: '🖨️',
    accentColor: 'from-indigo-600 to-violet-500',
  },
  {
    id: 'cat-5',
    name: 'Hóa Chất Khai Khoáng',
    slug: 'hoa-chat-khai-khoang',
    description: 'Thuốc tuyển quặng, chất tạo bọt, chất trợ lắng, hóa chất hòa tách và chế biến khoáng sản.',
    shortDesc: 'Thuốc tuyển quặng, chất trợ lắng...',
    image: '/images/categories/hoa-chat-khai-khoang.jpg',
    icon: '⛏️',
    accentColor: 'from-amber-600 to-yellow-500',
  },
  {
    id: 'cat-6',
    name: 'Hóa Chất Ngành Gốm Sứ',
    slug: 'hoa-chat-nganh-gom-su',
    description: 'Oxit màu kim loại, chất tạo men bóng, chất trợ chảy frit, phụ gia tăng cứng xương gốm sứ.',
    shortDesc: 'Oxit màu, men gốm, trợ chảy...',
    image: '/images/categories/hoa-chat-nganh-gom-su.jpg',
    icon: '🏺',
    accentColor: 'from-orange-600 to-amber-500',
  },
  {
    id: 'cat-7',
    name: 'Hóa Chất Keo - Gỗ Ép - Mút Xốp',
    slug: 'hoa-chat-nganh-keo-go-ep-mut-xop',
    description: 'Keo sữa PVA, keo UF, keo dán cạnh EVA, chất tạo bọt Polyol & TDI sản xuất đệm mút xốp.',
    shortDesc: 'Keo UF, Polyol, TDI, keo PVA...',
    image: '/images/categories/hoa-chat-nganh-keo-go-ep-mut-xop.jpg',
    icon: '🌲',
    accentColor: 'from-emerald-700 to-teal-600',
  },
  {
    id: 'cat-8',
    name: 'Hóa Chất Ngành Nhôm Kính',
    slug: 'hoa-chat-nganh-nhom-kinh',
    description: 'Chất tẩy rửa bề mặt nhôm, hóa chất nhuộm màu nhôm anode, axit khắc kính và keo kết dính.',
    shortDesc: 'Tẩy nhôm, nhuộm anode, khắc kính...',
    image: '/images/categories/hoa-chat-nganh-nhom-kinh.jpg',
    icon: '🔧',
    accentColor: 'from-cyan-600 to-blue-500',
  },
  {
    id: 'cat-9',
    name: 'Hóa Chất Ngành Nhựa',
    slug: 'hoa-chat-nganh-nhua',
    description: 'Phụ gia tăng dai, chất trợ gia công, chất bôi trơn, hạt màu masterbatch, chất ổn định nhiệt PVC.',
    shortDesc: 'Hạt màu masterbatch, tăng dai, PVC...',
    image: '/images/categories/hoa-chat-nganh-nhua.jpg',
    icon: '♻️',
    accentColor: 'from-emerald-600 to-lime-500',
  },
  {
    id: 'cat-10',
    name: 'Hóa Chất Ngành Sơn',
    slug: 'hoa-chat-nganh-son',
    description: 'Nhựa Acrylic, dung môi pha sơn, chất phân tán, chất làm đặc chống lắng, chất tạo màng sơn.',
    shortDesc: 'Nhựa Acrylic, chất phân tán, tạo màng...',
    image: '/images/categories/hoa-chat-nganh-son.jpg',
    icon: '🎭',
    accentColor: 'from-rose-600 to-pink-500',
  },
  {
    id: 'cat-11',
    name: 'Hóa Chất Ngành Tóc & Mỹ Phẩm',
    slug: 'hoa-chat-nganh-toc',
    description: 'Chất nhũ hóa, hoạt chất bề mặt dịu nhẹ, chất tạo đặc Carbomer, hương liệu và tinh dầu cao cấp.',
    shortDesc: 'Chất nhũ hóa, Carbomer, tạo bọt...',
    image: '/images/categories/hoa-chat-nganh-toc.jpg',
    icon: '💇',
    accentColor: 'from-pink-600 to-rose-400',
  },
  {
    id: 'cat-12',
    name: 'Hóa Chất Xốp Cắm Hoa Hữu Cơ',
    slug: 'hoa-chat-san-xuat-xop-cam-hoa-huu-co',
    description: 'Hóa chất chuyên dụng sản xuất bọt xốp phenolic cắm hoa, chất hút nước và giữ ẩm lâu dài.',
    shortDesc: 'Xốp phenolic giữ ẩm, bọt xốp cắm hoa...',
    image: '/images/categories/hoa-chat-san-xuat-xop-cam-hoa-huu-co.jpg',
    icon: '🌸',
    accentColor: 'from-green-600 to-emerald-500',
  },
  {
    id: 'cat-13',
    name: 'Hóa Chất Tẩy Rửa',
    slug: 'hoa-chat-tay-rua',
    description: 'LAS, SLES, Sodium Lauryl Sulfate, kiềm tẩy dầu mỡ công nghiệp, hóa chất tẩy rỉ sét chuyên dụng.',
    shortDesc: 'LAS, SLES, kiềm tẩy mỡ, tẩy rỉ...',
    image: '/images/categories/hoa-chat-tay-rua.jpg',
    icon: '🧼',
    accentColor: 'from-sky-600 to-teal-500',
  },
  {
    id: 'cat-14',
    name: 'Hóa Chất & Thiết Bị Thí Nghiệm',
    slug: 'hoa-chat-thi-nghiem',
    description: 'Hóa chất tinh khiết AR/PA từ Merck, Xilong; dụng cụ thủy tinh Borosilicate và máy đo chuẩn xác.',
    shortDesc: 'Hóa chất AR Merck/Xilong, thủy tinh...',
    image: '/images/categories/hoa-chat-thi-nghiem.jpg',
    icon: '🔬',
    accentColor: 'from-blue-700 to-indigo-600',
  },
  {
    id: 'cat-15',
    name: 'Hóa Chất Xây Dựng',
    slug: 'hoa-chat-xay-dung',
    description: 'Phụ gia giảm nước, chất đông kết nhanh, hợp chất chống thấm màng tinh thể, keo chà ron công nghiệp.',
    shortDesc: 'Phụ gia bê tông, chống thấm, đông kết...',
    image: '/images/categories/hoa-chat-xay-dung.jpg',
    icon: '🏗️',
    accentColor: 'from-stone-700 to-amber-700',
  },
  {
    id: 'cat-16',
    name: 'Hóa Chất Xi Mạ & Bề Mặt',
    slug: 'hoa-chat-xi-ma',
    description: 'Muối niken, axit cromic mạ crom, bóng mạ đồng, chất thụ động hóa bề mặt kẽm không chứa Cr6+.',
    shortDesc: 'Mạ kẽm, niken, crom, thụ động hóa...',
    image: '/images/categories/hoa-chat-xi-ma.jpg',
    icon: '⚙️',
    accentColor: 'from-teal-600 to-cyan-500',
  },
  {
    id: 'cat-17',
    name: 'Hóa Chất Xử Lý Nước Thải',
    slug: 'hoa-chat-xu-li-nuoc-thai',
    description: 'PAC keo tụ, Polymer Anion/Cation, Clo khử trùng, vi sinh xử lý nước thải sinh hoạt & công nghiệp.',
    shortDesc: 'PAC, Polymer, Clo, vi sinh xử lý...',
    image: '/images/categories/hoa-chat-xu-li-nuoc-thai.jpg',
    icon: '💧',
    accentColor: 'from-blue-600 to-cyan-600',
  },
  {
    id: 'cat-18',
    name: 'Nguyên Liệu Dược Phẩm',
    slug: 'nguyen-lieu-duoc-pham',
    description: 'Tá dược, hoạt chất dược dụng đạt chuẩn dược điển USP/BP/EP, đảm bảo chứng nhận COA/GMP.',
    shortDesc: 'Tá dược USP/BP, hoạt chất dược chuẩn...',
    image: '/images/categories/nguyen-lieu-duoc-pham.jpg',
    icon: '💊',
    accentColor: 'from-violet-600 to-purple-500',
  },
  {
    id: 'cat-19',
    name: 'Nguyên Liệu Đúc & Luyện Kim',
    slug: 'nguyen-lieu-nganh-duc-luyen-kim',
    description: 'Hợp kim Ferro, chất khử oxy, chất biến tính gang, bột bao phủ bề mặt và vật liệu chịu lửa cao cấp.',
    shortDesc: 'Ferro, chất biến tính gang, chịu lửa...',
    image: '/images/categories/nguyen-lieu-nganh-duc-luyen-kim.jpg',
    icon: '🔨',
    accentColor: 'from-orange-700 to-red-600',
  },
  {
    id: 'cat-20',
    name: 'Phụ Gia Thức Ăn Chăn Nuôi',
    slug: 'phu-gia-thuc-an-chan-nuoi',
    description: 'Lysine, Methionine, Choline Chloride, khoáng vi lượng, enzyme tiêu hóa kích thích tăng trọng gia súc.',
    shortDesc: 'Lysine, Methionine, premix khoáng...',
    image: '/images/categories/phu-gia-thuc-an-chan-nuoi.jpg',
    icon: '🐄',
    accentColor: 'from-lime-700 to-green-600',
  },
  {
    id: 'cat-21',
    name: 'Phụ Gia Thực Phẩm',
    slug: 'phu-gia-thuc-pham',
    description: 'Chất bảo quản Benzoate/Sorbate, chất điều vị, màu thực phẩm, chất nhũ hóa được cấp phép ATTP.',
    shortDesc: 'Chất bảo quản ATTP, hương liệu, nhũ hóa...',
    image: '/images/categories/phu-gia-thuc-pham.jpg',
    icon: '🍞',
    accentColor: 'from-yellow-600 to-orange-500',
  },
  {
    id: 'cat-22',
    name: 'Phụ Gia Nuôi Trồng Thủy Sản',
    slug: 'phu-gia-thuy-san',
    description: 'Khoáng tạt ao tôm, Yucca tiêu độc khử mùi khí độc NH3/H2S, men vi sinh xử lý đáy ao nuôi thủy sản.',
    shortDesc: 'Khoáng tạt, Yucca, vi sinh đáy ao...',
    image: '/images/categories/phu-gia-thuy-san.jpg',
    icon: '🐟',
    accentColor: 'from-cyan-600 to-blue-700',
  },
  {
    id: 'cat-23',
    name: 'Sản Phẩm Nổi Bật',
    slug: 'san-pham-noi-bat',
    description: 'Danh sách các hóa chất bán chạy nhất, sản lượng lớn, giá sỉ tốt nhất thị trường từ Hóa Chất Hải Vân.',
    shortDesc: 'Hóa chất bán chạy, chiết khấu cao...',
    image: '/images/categories/san-pham-noi-bat.jpg',
    icon: '⭐',
    accentColor: 'from-amber-500 to-yellow-400',
  },
]

export const DEFAULT_CATEGORIES: Category[] = CATEGORIES_DATA.map((c, i) => ({
  _id: c.id,
  name: c.name,
  slug: { current: c.slug },
  description: c.description,
  order: i + 1,
}))
